"""added processed at to studies

Revision ID: 10077a2e5193
Revises: 82f3a64b43eb
Create Date: 2024-12-17 19:58:02.317786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10077a2e5193'
down_revision = '82f3a64b43eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'processed_at')
    # ### end Alembic commands ###