"""updated study to include outcome measure

Revision ID: 402e9b96dee8
Revises: 90217f15bc0a
Create Date: 2025-01-03 16:40:35.790638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402e9b96dee8'
down_revision = '90217f15bc0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###