"""added pk to interventions

Revision ID: 52a2dc88f332
Revises: 776797d9e44b
Create Date: 2025-01-05 17:45:06.116692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a2dc88f332'
down_revision = '776797d9e44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interventions_pkey', 'interventions', type_='primary')

    # Add `description` to the primary key
    op.create_primary_key(
        'interventions_pkey',
        'interventions',
        ['id', 'study_id', 'description']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###