"""added pk to interventions

Revision ID: 776797d9e44b
Revises: abf3033b74f5
Create Date: 2025-01-05 17:36:10.730205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776797d9e44b'
down_revision = 'abf3033b74f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###