"""updated pk of outcome measure

Revision ID: 85159e059c73
Revises: 34774211a063
Create Date: 2025-01-03 20:22:19.466308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85159e059c73'
down_revision = '34774211a063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome_measures', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome_measures', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###