"""added fk to om2

Revision ID: 85832e5711e6
Revises: 91f375e0d9a8
Create Date: 2025-01-05 12:23:11.883451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85832e5711e6'
down_revision = '91f375e0d9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'outcome_measures', 'outcome_groups', ['group_study_id', 'group_id'], ['study_id', 'id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outcome_measures', type_='foreignkey')
    # ### end Alembic commands ###