"""added outcome measure model

Revision ID: 8fc5055f5493
Revises: 10077a2e5193
Create Date: 2025-01-03 14:50:55.992828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc5055f5493'
down_revision = '10077a2e5193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome_measures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('measure_title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_frame', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('analysis_population', sa.String(), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'group_id'], ['participant_groups.study_id', 'participant_groups.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome_measures')
    # ### end Alembic commands ###