"""updated outcome measures to include size

Revision ID: 90217f15bc0a
Revises: e38a5fdd9a6e
Create Date: 2025-01-03 16:36:33.970110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90217f15bc0a'
down_revision = 'e38a5fdd9a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome_groups', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome_groups', 'size')
    # ### end Alembic commands ###