"""added class title field to outcome measure

Revision ID: 909d20c546ef
Revises: 85159e059c73
Create Date: 2025-01-05 12:04:32.152585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909d20c546ef'
down_revision = '85159e059c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome_measures', sa.Column('class_title', sa.String(), nullable=False))
    op.drop_constraint('outcome_measures_group_study_id_group_id_fkey', 'outcome_measures', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('outcome_measures_group_study_id_group_id_fkey', 'outcome_measures', 'outcome_groups', ['group_study_id', 'group_id'], ['study_id', 'id'])
    op.drop_column('outcome_measures', 'class_title')
    # ### end Alembic commands ###