"""added fk to om

Revision ID: 91f375e0d9a8
Revises: d532153138b8
Create Date: 2025-01-05 12:19:57.960144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f375e0d9a8'
down_revision = 'd532153138b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###