"""updated participant demographic

Revision ID: 9976fc6c5859
Revises: 85832e5711e6
Create Date: 2025-01-05 15:46:23.719040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9976fc6c5859'
down_revision = '85832e5711e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant_demographics', 'study_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participant_demographics', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participant_demographics', 'measure_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participant_demographics', 'param_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('participant_demographics', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_demographics', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('participant_demographics', 'param_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participant_demographics', 'measure_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participant_demographics', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participant_demographics', 'study_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###