"""added medication tables

Revision ID: a3b179dcde51
Revises: d8cffc9273d3
Create Date: 2025-01-23 13:05:35.482300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b179dcde51'
down_revision = 'd8cffc9273d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.alter_column('adverse_events', 'severity',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('interventions', 'description',
    #            existing_type=sa.TEXT(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interventions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('adverse_events', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###