"""rm autoincrement = true

Revision ID: abf3033b74f5
Revises: 9976fc6c5859
Create Date: 2025-01-05 15:54:18.661459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf3033b74f5'
down_revision = '9976fc6c5859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baseline_characteristics', 'study_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('contacts', 'id')
    op.alter_column('participant_statistics', 'study_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participant_statistics', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participant_statistics', 'measure_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participant_statistics', 'param_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('participant_statistics', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_statistics', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('participant_statistics', 'param_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participant_statistics', 'measure_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participant_statistics', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('participant_statistics', 'study_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('contacts', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('baseline_characteristics', 'study_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###