"""added description to outcome

Revision ID: bd56b1fc2438
Revises: f985bcdae5cb
Create Date: 2025-01-06 13:19:08.142557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd56b1fc2438'
down_revision = 'f985bcdae5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('adverse_events', 'severity',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('interventions', 'description',
    #            existing_type=sa.TEXT(),
    #            nullable=True)
    op.add_column('outcomes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcomes', 'description')
    op.alter_column('interventions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('adverse_events', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###