"""added table to store visualizations

Revision ID: d8cffc9273d3
Revises: bd56b1fc2438
Create Date: 2025-01-13 11:24:22.937396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cffc9273d3'
down_revision = 'bd56b1fc2438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visualization_data',
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('study_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interventions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('adverse_events', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('visualization_data')
    # ### end Alembic commands ###