"""updated outcome measures

Revision ID: e38a5fdd9a6e
Revises: e73eaf72a39f
Create Date: 2025-01-03 16:07:10.538644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38a5fdd9a6e'
down_revision = 'e73eaf72a39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome_groups',
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('study_id', 'id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('outcome_measures', sa.Column('population_description', sa.Text(), nullable=True))
    op.drop_constraint('outcome_measures_study_id_group_id_fkey', 'outcome_measures', type_='foreignkey')
    op.create_foreign_key(None, 'outcome_measures', 'outcome_groups', ['group_id'], ['id'])
    op.drop_column('outcome_measures', 'analysis_population')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome_measures', sa.Column('analysis_population', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'outcome_measures', type_='foreignkey')
    op.create_foreign_key('outcome_measures_study_id_group_id_fkey', 'outcome_measures', 'participant_groups', ['study_id', 'group_id'], ['study_id', 'id'])
    op.drop_column('outcome_measures', 'population_description')
    op.drop_table('outcome_groups')
    # ### end Alembic commands ###