"""updated outcome measures with more fields

Revision ID: e73eaf72a39f
Revises: 8fc5055f5493
Create Date: 2025-01-03 15:31:14.420707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73eaf72a39f'
down_revision = '8fc5055f5493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome_measures', sa.Column('reporting_status', sa.String(), nullable=True))
    op.add_column('outcome_measures', sa.Column('param_type', sa.String(), nullable=True))
    op.add_column('outcome_measures', sa.Column('dispersion_type', sa.String(), nullable=True))
    op.add_column('outcome_measures', sa.Column('lower_limit', sa.Float(), nullable=True))
    op.add_column('outcome_measures', sa.Column('upper_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome_measures', 'upper_limit')
    op.drop_column('outcome_measures', 'lower_limit')
    op.drop_column('outcome_measures', 'dispersion_type')
    op.drop_column('outcome_measures', 'param_type')
    op.drop_column('outcome_measures', 'reporting_status')
    # ### end Alembic commands ###