"""added pk to adverse events

Revision ID: f985bcdae5cb
Revises: 8a3a5f5686e4
Create Date: 2025-01-06 12:25:31.543215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f985bcdae5cb'
down_revision = '8a3a5f5686e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("adverse_events_pkey", "adverse_events", type_="primary")

    op.create_primary_key(
        "adverse_events_pkey", "adverse_events", ["study_id", "group_id","term", "severity"]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interventions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###